### ISSUE TITLE
php8.2 support

### ISSUE THREAD

**Issue by lobodol** [scoutapp/scout-apm-symfony-bundle#30]
Hi there,

Do you plan to make it available for php8.2 soon?

Getting the following error when trying to install:

```
    - scoutapp/scout-apm-php[v8.0.0, ..., 8.2.3] require php 7.1.*|7.2.*|7.3.*|7.4.*|8.0.*|8.1.* -> your php version (8.2.0) does not satisfy that requirement.
    - scoutapp/scout-apm-php[8.3.0, ..., 8.7.0] require php 7.2.*|7.3.*|7.4.*|8.0.*|8.1.* -> your php version (8.2.0) does not satisfy that requirement.
```

Regards

**Comment by asgrim** [comment]
We already support PHP 8.2, you may need to use `--with-all-dependencies` flag with `composer update`. Let us know how you get on!

**Comment by lobodol** [comment]
I was missing the ext-sockets. I added it, ran composer with `--will-all-dependencies` and all went good.
Thanks for your help!

**Comment by asgrim** [comment]
Great, thanks for letting us know, I'll close this issue now.
